version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - checkout
  - run: echo "export GIT_TAG=${CIRCLE_TAG:=temp}" >> $BASH_ENV
  - setup_remote_docker:
  - run: cd circleci && docker build -t lkldocker/circleci:$GIT_TAG . && cd ..
  - run:
      name: freebsd image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 0 ]]; then
          cd circleci/freebsd11 && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-freebsd11-x86_64:$GIT_TAG . && cd ../..
        fi
  - run:
      name: x86_64 image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/x86_64 && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-x86_64:$GIT_TAG . && cd ../..
        fi
  - run:
      name: i386 image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/i386 && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-i386:$GIT_TAG . && cd ../..
        fi
  - run:
      name: mingw image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/mingw && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-mingw:$GIT_TAG . && cd ../..
        fi
  - run:
      name: android base image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/android && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-android:$GIT_TAG . && cd ../..
        fi
  - run:
      name: android arm32 image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/android/arm32 && docker build --build-arg IMAGE_NAME=lkldocker/circleci-android:$GIT_TAG -t lkldocker/circleci-android-arm32:$GIT_TAG . && cd ../../..
        fi
  - run:
      name: android arm64 image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/android/arm64 && docker build --build-arg IMAGE_NAME=lkldocker/circleci-android:$GIT_TAG -t lkldocker/circleci-android-arm64:$GIT_TAG . && cd ../../..
        fi
  - run:
      name: qemu x86_64 image build
      command: |
        if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
          cd circleci/qemu-x86_64 && docker build --build-arg IMAGE_NAME=lkldocker/circleci:$GIT_TAG -t lkldocker/circleci-qemu-x86_64:$GIT_TAG . && cd ../..
        fi
  - run: docker images
  - run:
      name: deploy to docker hub
      command: |
        if [[ -n $CIRCLE_TAG ]]; then
          if [[ $CIRCLE_PROJECT_USERNAME == lkl ]]; then
             docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
             if [[ $CIRCLE_NODE_INDEX == 0 ]]; then
                docker push lkldocker/circleci:$GIT_TAG
                docker push lkldocker/circleci-freebsd11-x86_64:$GIT_TAG
             fi
             if [[ $CIRCLE_NODE_INDEX == 1 ]]; then
                docker push lkldocker/circleci-x86_64:$GIT_TAG
                docker push lkldocker/circleci-qemu-x86_64:$GIT_TAG
                docker push lkldocker/circleci-i386:$GIT_TAG
                docker push lkldocker/circleci-mingw:$GIT_TAG
                docker push lkldocker/circleci-android:$GIT_TAG
                docker push lkldocker/circleci-android-arm32:$GIT_TAG
                docker push lkldocker/circleci-android-arm64:$GIT_TAG
             fi
          fi
        fi

## Customize the test machine
jobs:
  docker-build:
    parallelism: 2
    docker:
      - image: circleci/node:4.8.2
    environment:
    <<: *do_steps

workflows:
  version: 2
  build:
    jobs:
      - docker-build:
         filters:
          tags:
            only: /v.*/
